config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :songs
  resources :profiles
  resources :albums
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    # build random amount of songs
    # (1+rand(7)).ceil.times do |i|
    #   album.songs.build
    # end
    album = Album.new(songs: [Song.new, Song.new])
    @form = Forms::AlbumForm.new(album)
  end

  def edit
    album = Album.find(params[:id])
    @form = Forms::AlbumForm.new(album)
  end

  def create
    # how you could do it dynamically..(for now)
    # params[:album][:songs_attributes].size.times do |i|
    #   album.songs.build
    # end
    album = Album.new(songs: [Song.new, Song.new])
    @form = Forms::AlbumForm.new(album)

    if @form.validate(params["album"])
      @form.save
      redirect_to album_path(album)
    else
      render :new
    end
  end

  def update
    album = Album.find(params[:id])
    @form = Forms::AlbumForm.new(album)

    if @form.validate(params["album"])
      @form.save
      redirect_to album_path(album)
    else
      render :edit
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for @form do |f| %>
  <% if @form.errors.any? %>
    <div>
      <h3><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h3>

      <ul>
        <% @form.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title, "Album Title" %>
  <%= f.text_field :title %>

  <%= f.fields_for :songs do |song| %>
    <div>
      <%= song.label :name %>
      <%= song.text_field :name %>
      <%= song.label :issue %>
      <%= song.text_field :issue %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to Albums", albums_path, class: 'btn'  %>

app/views/albums/_form.html__2017-04-04_22.52.20.erb
<%= form_for(album) do |f| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h2>Ablums and Songs</h2>

<h4>1-n Example</h4>

<%= render "form" %>

app/views/albums/index.html.erb
<h2>Ablums and Songs</h2>

<h4>1-n Example</h4>

<ul>
  <% @albums.each do |album| %>
    <li>
      <%= link_to album_path(album) do %>
        <strong>Album Title:</strong>
        <%= album.title %>
        <ul>
          <% album.songs.each do |song| %>
            <li>
              <strong>Song Name:</strong>
              <%= song.name %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "New Album", new_album_path, class: 'btn' %>

app/views/albums/new.html.erb
<h2>Ablums and Songs</h2>

<h4>1-n Example</h4>

<%= render "form" %>

app/views/albums/show.html.erb
<h2>Ablums and Songs</h2>

<h4>1-n Example</h4>

<h3>Album:</h3>
<%= @album.inspect %>

<% if @album.songs.any? %>
  <h3>Songs: </h3>
  <ul>
    <% @album.songs.each do |song| %>
      <li>
        <%= song.inspect %>
      </li>
    <% end %>
  </ul>
<% end %>

<br />

<%= link_to "Edit Album", edit_album_path(@album), class: 'btn'  %>
<br />
<%= link_to "Back to Albums", albums_path, class: 'btn'  %>